import { ArrowDownRight, ArrowUpRight, CalendarDays, Download, FileText, TrendingUp } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { PageHeader } from '../../components/ui/PageHeader'
import { monthlyPerformance, specialtyData } from '../../data/mockData'

const attendanceData = [
  { label: 'Comparecimento', value: 87, color: '#167f79' },
  { label: 'Faltas', value: 8, color: '#e19a62' },
  { label: 'Cancelamentos', value: 5, color: '#d6dfdd' },
]

export function ReportsPage() {
  return (
    <section className="page-content">
      <PageHeader eyebrow="INTELIGÊNCIA DA UNIDADE" title="Relatórios" description="Transforme os dados da rotina em decisões para melhorar o cuidado." actions={<><button className="secondary-button"><CalendarDays size={17} /> Mar — Ago 2026</button><button className="primary-button page-primary"><Download size={17} /> Exportar</button></>} />
      <div className="report-kpis"><article><span>Atendimentos no período</span><strong>2.023</strong><p className="trend-up"><ArrowUpRight size={14} /> 12,4% <em>vs. período anterior</em></p></article><article><span>Taxa de comparecimento</span><strong>87,2%</strong><p className="trend-up"><ArrowUpRight size={14} /> 5,8% <em>de evolução</em></p></article><article><span>Tempo médio de espera</span><strong>6,4 <small>dias</small></strong><p className="trend-down"><ArrowDownRight size={14} /> 2,1 dias <em>de redução</em></p></article><article><span>Altas terapêuticas</span><strong>162</strong><p className="trend-up"><ArrowUpRight size={14} /> 18,7% <em>no período</em></p></article></div>
      <div className="report-grid">
        <section className="panel chart-panel wide-chart"><div className="chart-heading"><div><h2>Evolução dos atendimentos</h2><p>Atendimentos realizados e altas por mês</p></div><span className="chart-growth"><TrendingUp size={15} /> Crescimento consistente</span></div><div className="main-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthlyPerformance} margin={{ left: -20, right: 10, top: 12 }}><defs><linearGradient id="attendanceGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#167f79" stopOpacity={0.28} /><stop offset="100%" stopColor="#167f79" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e9efed" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#81908e', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#81908e', fontSize: 10 }} /><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid #e1eae8', boxShadow: '0 12px 30px rgba(23,51,52,.1)', fontSize: 12 }} /><Area type="monotone" dataKey="atendimentos" stroke="#167f79" strokeWidth={3} fill="url(#attendanceGradient)" /></AreaChart></ResponsiveContainer></div></section>
        <section className="panel chart-panel"><div className="chart-heading"><div><h2>Demanda por especialidade</h2><p>Distribuição dos pacientes ativos</p></div></div><div className="donut-wrap"><ResponsiveContainer width="55%" height={190}><PieChart><Pie data={specialtyData} dataKey="value" innerRadius={52} outerRadius={77} paddingAngle={3} stroke="none">{specialtyData.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip contentStyle={{ borderRadius: 10, border: '1px solid #e1eae8', fontSize: 11 }} /></PieChart></ResponsiveContainer><div className="donut-center"><strong>248</strong><span>pacientes</span></div><div className="chart-legend">{specialtyData.map((item) => <div key={item.name}><span><i style={{ background: item.color }} />{item.name}</span><strong>{item.value}%</strong></div>)}</div></div></section>
        <section className="panel chart-panel"><div className="chart-heading"><div><h2>Adesão aos atendimentos</h2><p>Comportamento da agenda em agosto</p></div></div><div className="bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={attendanceData} margin={{ left: -30, right: 8 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e9efed" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#81908e', fontSize: 9 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#81908e', fontSize: 9 }} /><Tooltip cursor={{ fill: '#f6f9f8' }} contentStyle={{ borderRadius: 10, border: '1px solid #e1eae8', fontSize: 11 }} /><Bar dataKey="value" radius={[7, 7, 0, 0]}>{attendanceData.map((item) => <Cell key={item.label} fill={item.color} />)}</Bar></BarChart></ResponsiveContainer></div></section>
        <section className="panel insights-panel"><div className="chart-heading"><div><h2>Destaques do período</h2><p>Leituras importantes para a gestão</p></div></div><div className="insight-item positive-insight"><span>01</span><div><strong>Ortopedia concentra a maior demanda</strong><p>42% dos pacientes ativos. Reavalie a oferta de horários às terças e quintas.</p></div></div><div className="insight-item"><span>02</span><div><strong>Menor índice de faltas do semestre</strong><p>As confirmações antecipadas reduziram ausências em 5,8%.</p></div></div><div className="insight-item"><span>03</span><div><strong>Fila neurológica exige atenção</strong><p>Dois pacientes de alta prioridade aguardam há mais de uma semana.</p></div></div></section>
      </div>
      <section className="reports-library"><div><span><FileText size={19} /></span><div><h2>Relatórios prontos</h2><p>Documentos recorrentes para auditoria e gestão.</p></div></div><div className="report-file"><div><strong>Produção ambulatorial</strong><span>PDF • Agosto 2026</span></div><button><Download size={16} /></button></div><div className="report-file"><div><strong>Fila de espera consolidada</strong><span>XLSX • Atualizado hoje</span></div><button><Download size={16} /></button></div><div className="report-file"><div><strong>Indicadores de adesão</strong><span>PDF • 2º trimestre</span></div><button><Download size={16} /></button></div></section>
    </section>
  )
}
